name: "Build MCP Server and Deploy"
on:
    push:
        branches:
            - main
jobs:
    build-server:
        name: "Build MCP Server"
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            id-token: write
        steps:
            - name: Azure login
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                  enable-AzPSSession: true

            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to ACR
              env:
                  ACR_LOGIN_SERVER: ${{ vars.ACR_LOGIN_SERVER }}
              run: |
                  az acr login -n $ACR_LOGIN_SERVER
            - name: Create tag string
              run: |
                  echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

            # This will push the docker images to the GitHub container registry
            # You will need to give actions permission to push there first
            - name: Build and push
              id: docker_build
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  tags: |
                      ${{ vars.ACR_LOGIN_SERVER }}/${{ env.REPO }}:latest
                      ${{ vars.ACR_LOGIN_SERVER }}/${{ env.REPO }}:dev-${{ github.run_number }}
